# Generated by Django 4.0.4 on 2022-05-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_category_alter_employee_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='categoria',
            field=models.ManyToManyField(to='erp.category'),
        ),
    ]
